# -*- coding: utf-8 -*-
"""Trabajo_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuBOdZxAtt-3d-JvPVUWuclWPROO7ZEk

# Trabajo Final — Parte 1/1
# Workflow reproducible para convocatorias del OECE

## Título provisional
**Workflow reproducible para la inspección, inventario estructural y preparación de descargas del módulo de convocatorias del OECE**

## Propósito de esta parte
Esta primera parte reinicia el Trabajo Final desde cero y fija una base técnica estable para el resto del proyecto. Su objetivo no es todavía descargar masivamente ni ensamblar bases, sino construir de manera rigurosa el entorno de trabajo, verificar la fuente oficial, inspeccionar la estructura visible de la subpágina de convocatorias y dejar un manifest inicial reproducible.

## Objeto de trabajo
El objeto no es la contratación pública peruana en abstracto ni todos los módulos del portal OECE. El objeto específico es la arquitectura visible y descargable del módulo **“Datos de la Convocatoria o Invitación”**, organizada por año y por tipo de descarga.

## Secuencia metodológica de esta parte
**entorno → rutas → fuente oficial → HTML bruto → HTML renderizado → inventario estructural → manifest inicial**

## Resultado esperado
Al finalizar esta parte, el proyecto debe quedar con carpetas creadas, evidencia web guardada, años detectados, botones inventariados y una tabla maestra inicial lista para sostener la fase posterior de descarga controlada.
"""

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
import pandas as pd
import numpy as np
import re
import json
import time
import unicodedata
from bs4 import BeautifulSoup
import requests

pd.set_option("display.max_columns", 250)
pd.set_option("display.width", 260)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# RUTA BASE DEL PROYECTO
# ============================================================

BASE = Path("/content/drive/MyDrive/IA Generativa para CCSS/Trabajo Final")

CARPETAS = [
    "00_admin",
    "01_insumos",
    "01_insumos/capturas_portal",
    "01_insumos/indicaciones_curso",
    "01_insumos/referencias_teoricas",
    "02_fuente_web",
    "02_fuente_web/html_guardado",
    "02_fuente_web/enlaces_detectados",
    "02_fuente_web/metadata_descargas",
    "02_fuente_web/logs_scraping",
    "03_datos_brutos",
    "03_datos_brutos/convocatorias",
    "04_datos_procesados",
    "04_datos_procesados/auditorias",
    "04_datos_procesados/tablas_limpias",
    "04_datos_procesados/tablas_unificadas",
    "04_datos_procesados/variables_derivadas",
    "05_notebooks",
    "06_scripts",
    "07_resultados",
    "07_resultados/tablas",
    "07_resultados/figuras",
    "07_resultados/resumenes",
    "08_presentacion",
    "08_presentacion/imagenes",
    "08_presentacion/borradores",
    "09_entrega"
]

for carpeta in CARPETAS:
    (BASE / carpeta).mkdir(parents=True, exist_ok=True)

# Rutas frecuentes
RUTA_ADMIN = BASE / "00_admin"
RUTA_INSUMOS = BASE / "01_insumos"
RUTA_FUENTE = BASE / "02_fuente_web"
RUTA_HTML = RUTA_FUENTE / "html_guardado"
RUTA_ENLACES = RUTA_FUENTE / "enlaces_detectados"
RUTA_META = RUTA_FUENTE / "metadata_descargas"
RUTA_LOGS = RUTA_FUENTE / "logs_scraping"
RUTA_BRUTOS = BASE / "03_datos_brutos" / "convocatorias"
RUTA_PROCESADOS = BASE / "04_datos_procesados"
RUTA_RESULTADOS = BASE / "07_resultados"
RUTA_RESULTADOS_TABLAS = RUTA_RESULTADOS / "tablas"
RUTA_RESULTADOS_FIGURAS = RUTA_RESULTADOS / "figuras"
RUTA_RESULTADOS_RESUMENES = RUTA_RESULTADOS / "resumenes"

print("Proyecto inicializado en:")
print(BASE)

print("\nEstructura principal:")
for carpeta in [
    "00_admin",
    "01_insumos",
    "02_fuente_web",
    "03_datos_brutos",
    "04_datos_procesados",
    "05_notebooks",
    "06_scripts",
    "07_resultados",
    "08_presentacion",
    "09_entrega"
]:
    print("-", carpeta)

# ============================================================
# FUNCIONES AUXILIARES
# ============================================================

def normalizar_texto(texto: str) -> str:
    texto = str(texto).strip().lower()
    texto = "".join(
        ch for ch in unicodedata.normalize("NFD", texto)
        if unicodedata.category(ch) != "Mn"
    )
    texto = re.sub(r"[^a-z0-9._-]+", "_", texto)
    return texto

def normalizar_columna(col: str) -> str:
    col = str(col).strip().lower()
    col = "".join(
        ch for ch in unicodedata.normalize("NFD", col)
        if unicodedata.category(ch) != "Mn"
    )
    col = re.sub(r"[^a-z0-9]+", "_", col)
    col = re.sub(r"_+", "_", col).strip("_")
    return col

def guardar_texto(ruta: Path, contenido: str):
    ruta.parent.mkdir(parents=True, exist_ok=True)
    with open(ruta, "w", encoding="utf-8") as f:
        f.write(contenido)

def guardar_json(obj, ruta: Path):
    ruta.parent.mkdir(parents=True, exist_ok=True)
    with open(ruta, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)

def guardar_csv(df: pd.DataFrame, ruta: Path):
    ruta.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(ruta, index=False, encoding="utf-8")

def mostrar_resumen(df: pd.DataFrame, nombre: str, n=5):
    print(f"{nombre}: {df.shape[0]:,} filas × {df.shape[1]:,} columnas")
    display(df.head(n))

def mostrar_arbol(ruta: Path, max_nivel=2, nivel=0):
    if nivel > max_nivel:
        return
    prefijo = "    " * nivel
    print(f"{prefijo}- {ruta.name}/")
    for sub in sorted(ruta.iterdir()):
        if sub.is_dir():
            mostrar_arbol(sub, max_nivel=max_nivel, nivel=nivel + 1)

mostrar_arbol(BASE, max_nivel=2)

# ============================================================
# URLS OFICIALES DE TRABAJO
# ============================================================

URL_PORTAL = "https://bi.seace.gob.pe/pentaho/api/repos/%3Apublic%3Aportal%3Adatosabiertos.html/content?userid=public&password=key"
URL_CONVOCATORIAS = "https://bi.seace.gob.pe/pentaho/api/repos/%3Apublic%3Aportal%3Adataset.html/content?userid=public&password=key&pagina=convocatorias"
URL_REFERENCIA_GOB = "https://www.gob.pe/14272-acceder-al-portal-de-datos-abiertos-del-osce"

tabla_urls = pd.DataFrame([
    {"objeto": "portal_principal", "url": URL_PORTAL, "descripcion": "Portada del Portal de Datos Abiertos del OECE"},
    {"objeto": "subpagina_convocatorias", "url": URL_CONVOCATORIAS, "descripcion": "Módulo Datos de la Convocatoria o Invitación"},
    {"objeto": "referencia_institucional", "url": URL_REFERENCIA_GOB, "descripcion": "Ficha oficial del servicio en gob.pe"},
])

guardar_csv(tabla_urls, RUTA_META / "tf_p1_urls_trabajo.csv")
mostrar_resumen(tabla_urls, "tabla_urls")

# ============================================================
# DESCARGA DEL HTML BRUTO
# ============================================================

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/123.0.0.0 Safari/537.36"
    )
}

def descargar_html(url: str, timeout=60):
    r = requests.get(url, headers=HEADERS, timeout=timeout)
    r.raise_for_status()
    return r

resp_portal = descargar_html(URL_PORTAL)
resp_conv = descargar_html(URL_CONVOCATORIAS)

html_portal = resp_portal.text
html_conv = resp_conv.text

guardar_texto(RUTA_HTML / "tf_p1_portal_principal_raw.html", html_portal)
guardar_texto(RUTA_HTML / "tf_p1_convocatorias_raw.html", html_conv)

meta_fuente = pd.DataFrame([
    {
        "pagina": "portal_principal",
        "status_code": resp_portal.status_code,
        "content_type": resp_portal.headers.get("Content-Type"),
        "url_final": resp_portal.url,
        "n_caracteres_html": len(html_portal)
    },
    {
        "pagina": "subpagina_convocatorias",
        "status_code": resp_conv.status_code,
        "content_type": resp_conv.headers.get("Content-Type"),
        "url_final": resp_conv.url,
        "n_caracteres_html": len(html_conv)
    }
])

guardar_csv(meta_fuente, RUTA_META / "tf_p1_meta_fuente_raw.csv")
mostrar_resumen(meta_fuente, "meta_fuente")

# ============================================================
# INSPECCIÓN BÁSICA DEL HTML BRUTO
# ============================================================

soup_portal = BeautifulSoup(html_portal, "lxml")
soup_conv = BeautifulSoup(html_conv, "lxml")

def extraer_elementos_basicos(soup, pagina):
    titulo = soup.title.get_text(" ", strip=True) if soup.title else None

    encabezados = []
    for tag in soup.find_all(["h1", "h2", "h3"]):
        texto = tag.get_text(" ", strip=True)
        if texto:
            encabezados.append({"pagina": pagina, "tag": tag.name, "texto": texto})

    enlaces = []
    for a in soup.find_all("a", href=True):
        texto = a.get_text(" ", strip=True)
        href = a.get("href")
        enlaces.append({
            "pagina": pagina,
            "texto": texto,
            "href": href
        })

    return titulo, pd.DataFrame(encabezados), pd.DataFrame(enlaces)

titulo_portal, encabezados_portal, enlaces_portal = extraer_elementos_basicos(soup_portal, "portal_principal")
titulo_conv, encabezados_conv, enlaces_conv = extraer_elementos_basicos(soup_conv, "subpagina_convocatorias")

tabla_titulos = pd.DataFrame([
    {"pagina": "portal_principal", "titulo": titulo_portal},
    {"pagina": "subpagina_convocatorias", "titulo": titulo_conv},
])

df_encabezados = pd.concat([encabezados_portal, encabezados_conv], ignore_index=True)
df_enlaces = pd.concat([enlaces_portal, enlaces_conv], ignore_index=True)

guardar_csv(tabla_titulos, RUTA_ENLACES / "tf_p1_titulos_paginas.csv")
guardar_csv(df_encabezados, RUTA_ENLACES / "tf_p1_encabezados_html_raw.csv")
guardar_csv(df_enlaces, RUTA_ENLACES / "tf_p1_enlaces_html_raw.csv")

print("Título portal principal:", titulo_portal)
print("Título subpágina:", titulo_conv)

mostrar_resumen(df_encabezados, "df_encabezados")
mostrar_resumen(df_enlaces, "df_enlaces")

# ============================================================
# INSTALACIÓN DE SELENIUM Y CHROME
# ============================================================

!pip -q install selenium webdriver-manager
!wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!dpkg -i google-chrome-stable_current_amd64.deb > /dev/null 2>&1 || true
!apt-get -f install -y -qq > /dev/null 2>&1

# ============================================================
# CONFIGURACIÓN DEL DRIVER
# ============================================================

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

def crear_driver():
    opciones = Options()
    opciones.add_argument("--headless=new")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.binary_location = "/usr/bin/google-chrome"

    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=opciones)
    return driver

driver = crear_driver()
driver.get(URL_CONVOCATORIAS)
time.sleep(7)

html_renderizado = driver.page_source
texto_renderizado = driver.find_element(By.TAG_NAME, "body").text

guardar_texto(RUTA_HTML / "tf_p1_convocatorias_renderizado.html", html_renderizado)
guardar_texto(RUTA_HTML / "tf_p1_convocatorias_renderizado.txt", texto_renderizado)

print("Longitud HTML renderizado:", len(html_renderizado))
print("Primeros 1000 caracteres del texto visible:\n")
print(texto_renderizado[:1000])

# ============================================================
# DETECCIÓN ROBUSTA DE AÑOS VISIBLES
# ============================================================

anios_detectados = sorted(set(re.findall(r"\b20\d{2}\b", texto_renderizado)))
anios_detectados = [a for a in anios_detectados if 2010 <= int(a) <= 2100]

df_anios_detectados = pd.DataFrame({"anio_detectado": anios_detectados})
guardar_csv(df_anios_detectados, RUTA_META / "tf_p1_anios_detectados_render.csv")
mostrar_resumen(df_anios_detectados, "df_anios_detectados")

# ============================================================
# MAPA DE BOTONES ESPERADOS
# ============================================================

MAPA_BOTONES = {
    "DESCARGAR TODOS LOS PROCESOS": "todos_los_procesos",
    "DESCARGAR SOLO SUBASTA INVERSA ELECTRÓNICA": "solo_subasta_inversa_electronica",
    "DESCARGAR SOLO SUBASTA INVERSA ELECTRONICA": "solo_subasta_inversa_electronica",
    "DESCARGAR SOLO CONTRATACIÓN DIRECTA": "solo_contratacion_directa",
    "DESCARGAR SOLO CONTRATACION DIRECTA": "solo_contratacion_directa",
}

def normalizar_espacios(texto: str) -> str:
    return re.sub(r"\s+", " ", str(texto)).strip()

def obtener_contenedor_anio(driver, anio: str, max_niveles=8):
    year_xpath = f"//*[normalize-space(text())='{anio}']"
    year_el = driver.find_element(By.XPATH, year_xpath)

    actual = year_el
    for _ in range(max_niveles):
        texto = normalizar_espacios(actual.text).upper()
        botones = actual.find_elements(By.XPATH, ".//button | .//a")
        textos_botones = [
            normalizar_espacios(b.text).upper()
            for b in botones
            if normalizar_espacios(b.text)
        ]

        if "FORMATO EXCEL" in texto and any("DESCARGAR" in tb for tb in textos_botones):
            return actual

        actual = actual.find_element(By.XPATH, "..")

    return None

def extraer_botones_contenedor(contenedor):
    candidatos = contenedor.find_elements(By.XPATH, ".//button | .//a")
    resultados = []

    for i, el in enumerate(candidatos, start=1):
        texto = normalizar_espacios(el.text)
        if not texto:
            continue
        if "DESCARGAR" not in texto.upper():
            continue

        resultados.append({
            "orden_boton": i,
            "texto_boton": texto,
            "tipo_descarga": MAPA_BOTONES.get(texto.upper()),
            "tag": el.tag_name
        })

    return pd.DataFrame(resultados)

inventario_botones = []

for anio in anios_detectados:
    try:
        contenedor = obtener_contenedor_anio(driver, anio)
        if contenedor is None:
            inventario_botones.append({
                "anio": anio,
                "estado": "contenedor_no_detectado",
                "texto_boton": None,
                "tipo_descarga": None,
                "tag": None
            })
            continue

        df_botones = extraer_botones_contenedor(contenedor)

        if df_botones.empty:
            inventario_botones.append({
                "anio": anio,
                "estado": "sin_botones_detectados",
                "texto_boton": None,
                "tipo_descarga": None,
                "tag": None
            })
        else:
            for _, row in df_botones.iterrows():
                inventario_botones.append({
                    "anio": anio,
                    "estado": "ok",
                    "texto_boton": row["texto_boton"],
                    "tipo_descarga": row["tipo_descarga"],
                    "tag": row["tag"]
                })
    except Exception as e:
        inventario_botones.append({
            "anio": anio,
            "estado": "error",
            "texto_boton": None,
            "tipo_descarga": None,
            "tag": None,
            "error": str(e)
        })

df_inventario_botones = pd.DataFrame(inventario_botones)
guardar_csv(df_inventario_botones, RUTA_ENLACES / "tf_p1_inventario_botones_renderizados.csv")
mostrar_resumen(df_inventario_botones, "df_inventario_botones", n=20)

driver.quit()
print("Driver cerrado correctamente.")

# ============================================================
# ESTRUCTURA ESPERADA POR AÑO
# ============================================================

TIPOS_DESCARGA_ESPERADOS = [
    "todos_los_procesos",
    "solo_subasta_inversa_electronica",
    "solo_contratacion_directa"
]

estructura_esperada = pd.DataFrame(
    [(anio, tipo) for anio in anios_detectados for tipo in TIPOS_DESCARGA_ESPERADOS],
    columns=["anio", "tipo_descarga"]
)

estructura_visible = (
    df_inventario_botones.loc[df_inventario_botones["estado"] == "ok", ["anio", "tipo_descarga"]]
    .dropna()
    .drop_duplicates()
    .copy()
)
estructura_visible["visible_en_render"] = 1

estructura_control = estructura_esperada.merge(
    estructura_visible,
    on=["anio", "tipo_descarga"],
    how="left"
)

estructura_control["visible_en_render"] = estructura_control["visible_en_render"].fillna(0).astype(int)

guardar_csv(estructura_control, RUTA_META / "tf_p1_estructura_control_convocatorias.csv")
mostrar_resumen(estructura_control, "estructura_control", n=20)

# ============================================================
# MANIFEST INICIAL DEL WORKFLOW
# ============================================================

def ruta_anio(anio: str) -> Path:
    ruta = RUTA_BRUTOS / anio
    ruta.mkdir(parents=True, exist_ok=True)
    return ruta

def nombre_archivo_estandar(anio: str, tipo_descarga: str, extension=".xlsx") -> str:
    return f"oece_convocatorias_{anio}_{tipo_descarga}{extension}"

manifest_inicial = estructura_control.copy()
manifest_inicial["url_fuente"] = URL_CONVOCATORIAS
manifest_inicial["ruta_destino"] = manifest_inicial.apply(
    lambda x: str(ruta_anio(x["anio"]) / nombre_archivo_estandar(x["anio"], x["tipo_descarga"])),
    axis=1
)
manifest_inicial["archivo_esperado"] = manifest_inicial.apply(
    lambda x: nombre_archivo_estandar(x["anio"], x["tipo_descarga"]),
    axis=1
)
manifest_inicial["estado_descarga"] = "pendiente"
manifest_inicial["estado_auditoria"] = "pendiente"
manifest_inicial["estado_lectura"] = "pendiente"
manifest_inicial["estado_integracion"] = "pendiente"
manifest_inicial["es_paquete_principal"] = (manifest_inicial["tipo_descarga"] == "todos_los_procesos").astype(int)

guardar_csv(manifest_inicial, RUTA_ADMIN / "manifest_inicial_workflow_convocatorias.csv")
mostrar_resumen(manifest_inicial, "manifest_inicial", n=20)

# ============================================================
# BITÁCORA METODOLÓGICA
# ============================================================

bitacora_p1 = pd.DataFrame([
    {
        "paso": 1,
        "descripcion": "Creación de la arquitectura de carpetas del proyecto",
        "salida_principal": "Estructura base en Google Drive"
    },
    {
        "paso": 2,
        "descripcion": "Formalización de URLs oficiales de trabajo",
        "salida_principal": "Tabla de URLs"
    },
    {
        "paso": 3,
        "descripcion": "Descarga y guardado del HTML bruto del portal y de la subpágina",
        "salida_principal": "Archivos HTML raw"
    },
    {
        "paso": 4,
        "descripcion": "Inspección básica de títulos, encabezados y enlaces",
        "salida_principal": "Inventario inicial de elementos HTML"
    },
    {
        "paso": 5,
        "descripcion": "Renderizado de la subpágina con Selenium",
        "salida_principal": "HTML y texto visible renderizados"
    },
    {
        "paso": 6,
        "descripcion": "Detección robusta de años visibles y botones de descarga",
        "salida_principal": "Inventario renderizado por año y tipo"
    },
    {
        "paso": 7,
        "descripcion": "Construcción del manifest inicial del workflow",
        "salida_principal": "Manifest reproducible de combinaciones año × tipo"
    }
])

guardar_csv(bitacora_p1, RUTA_LOGS / "tf_p1_bitacora_metodologica.csv")
mostrar_resumen(bitacora_p1, "bitacora_p1", n=10)

print("Parte 1/1 completada correctamente.")
print("\nArchivos clave generados:")
print("-", RUTA_HTML / "tf_p1_portal_principal_raw.html")
print("-", RUTA_HTML / "tf_p1_convocatorias_raw.html")
print("-", RUTA_HTML / "tf_p1_convocatorias_renderizado.html")
print("-", RUTA_ENLACES / "tf_p1_inventario_botones_renderizados.csv")
print("-", RUTA_ADMIN / "manifest_inicial_workflow_convocatorias.csv")

"""# Trabajo Final — Parte 2/3
# Descarga controlada multianual, inventario físico y auditoría técnica inicial

## Propósito de esta parte
Esta segunda parte transforma la inspección estructural de la Parte 1/1 en una fase operativa de descarga controlada y auditable. El objetivo no es todavía ensamblar ni analizar la base final, sino ejecutar de manera rigurosa el workflow de obtención de archivos del módulo de convocatorias del OECE.

## Alcance técnico
Esta parte trabajará sobre **todos los años visibles detectados** en la Parte 1/1 y sobre los tipos de descarga efectivamente observados en la página renderizada.

## Secuencia metodológica
**manifest inicial → plan de descarga → Selenium → descarga controlada → renombrado → inventario físico → auditoría técnica → actualización del manifest**

## Resultado esperado
Al finalizar esta parte, el proyecto debe contar con:
- archivos descargados y renombrados por año;
- inventario físico reproducible;
- auditoría técnica inicial de los Excels;
- manifest actualizado con estados de descarga y auditoría.
"""

from pathlib import Path
import pandas as pd
import numpy as np
import re
import os
import json
import time
import shutil
import unicodedata

pd.set_option("display.max_columns", 250)
pd.set_option("display.width", 260)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# RUTA BASE Y CARPETAS DEL PROYECTO
# ============================================================

BASE = Path("/content/drive/MyDrive/IA Generativa para CCSS/Trabajo Final")

RUTA_ADMIN = BASE / "00_admin"
RUTA_FUENTE = BASE / "02_fuente_web"
RUTA_HTML = RUTA_FUENTE / "html_guardado"
RUTA_ENLACES = RUTA_FUENTE / "enlaces_detectados"
RUTA_META = RUTA_FUENTE / "metadata_descargas"
RUTA_LOGS = RUTA_FUENTE / "logs_scraping"

RUTA_BRUTOS = BASE / "03_datos_brutos" / "convocatorias"

RUTA_PROCESADOS = BASE / "04_datos_procesados"
RUTA_AUDITORIAS = RUTA_PROCESADOS / "auditorias"
RUTA_TABLAS_LIMPIAS = RUTA_PROCESADOS / "tablas_limpias"
RUTA_TABLAS_UNIFICADAS = RUTA_PROCESADOS / "tablas_unificadas"
RUTA_VARIABLES = RUTA_PROCESADOS / "variables_derivadas"

RUTA_RESULTADOS = BASE / "07_resultados"
RUTA_RESULTADOS_TABLAS = RUTA_RESULTADOS / "tablas"
RUTA_RESULTADOS_FIGURAS = RUTA_RESULTADOS / "figuras"
RUTA_RESULTADOS_RESUMENES = RUTA_RESULTADOS / "resumenes"

for ruta in [
    RUTA_ADMIN, RUTA_FUENTE, RUTA_HTML, RUTA_ENLACES, RUTA_META, RUTA_LOGS,
    RUTA_BRUTOS, RUTA_PROCESADOS, RUTA_AUDITORIAS, RUTA_TABLAS_LIMPIAS,
    RUTA_TABLAS_UNIFICADAS, RUTA_VARIABLES, RUTA_RESULTADOS, RUTA_RESULTADOS_TABLAS,
    RUTA_RESULTADOS_FIGURAS, RUTA_RESULTADOS_RESUMENES
]:
    ruta.mkdir(parents=True, exist_ok=True)

# ============================================================
# ARCHIVOS DE ENTRADA PRODUCIDOS EN LA PARTE 1/1
# ============================================================

RUTA_MANIFEST_INICIAL = RUTA_ADMIN / "manifest_inicial_workflow_convocatorias.csv"
RUTA_INVENTARIO_BOTONES = RUTA_ENLACES / "tf_p1_inventario_botones_renderizados.csv"
RUTA_ESTRUCTURA_CONTROL = RUTA_META / "tf_p1_estructura_control_convocatorias.csv"

for ruta in [RUTA_MANIFEST_INICIAL, RUTA_INVENTARIO_BOTONES, RUTA_ESTRUCTURA_CONTROL]:
    if not ruta.exists():
        raise FileNotFoundError(f"No existe el archivo requerido: {ruta}")

manifest_inicial = pd.read_csv(RUTA_MANIFEST_INICIAL)
inventario_botones = pd.read_csv(RUTA_INVENTARIO_BOTONES)
estructura_control = pd.read_csv(RUTA_ESTRUCTURA_CONTROL)

manifest_inicial["anio"] = manifest_inicial["anio"].astype(str)
inventario_botones["anio"] = inventario_botones["anio"].astype(str)
estructura_control["anio"] = estructura_control["anio"].astype(str)

print("Artefactos previos cargados correctamente.")
print("Manifest inicial:", manifest_inicial.shape)
print("Inventario de botones:", inventario_botones.shape)
print("Estructura control:", estructura_control.shape)

display(manifest_inicial.head())
display(inventario_botones.head())

# ============================================================
# URLS Y PARÁMETROS DE LA PARTE 2/3
# ============================================================

URL_CONVOCATORIAS = "https://bi.seace.gob.pe/pentaho/api/repos/%3Apublic%3Aportal%3Adataset.html/content?userid=public&password=key&pagina=convocatorias"

TIPOS_DESCARGA_ESPERADOS = [
    "todos_los_procesos",
    "solo_subasta_inversa_electronica",
    "solo_contratacion_directa"
]

MAPA_BOTONES = {
    "DESCARGAR TODOS LOS PROCESOS": "todos_los_procesos",
    "DESCARGAR SOLO SUBASTA INVERSA ELECTRÓNICA": "solo_subasta_inversa_electronica",
    "DESCARGAR SOLO SUBASTA INVERSA ELECTRONICA": "solo_subasta_inversa_electronica",
    "DESCARGAR SOLO CONTRATACIÓN DIRECTA": "solo_contratacion_directa",
    "DESCARGAR SOLO CONTRATACION DIRECTA": "solo_contratacion_directa"
}

# Parámetro de seguridad:
# False -> si el archivo ya existe, no lo vuelve a descargar
# True  -> reemplaza archivo existente
REEMPLAZAR_DESCARGAS = False

# Orden lógico de paquetes para el plan de descarga
ORDEN_TIPOS = {
    "todos_los_procesos": 1,
    "solo_subasta_inversa_electronica": 2,
    "solo_contratacion_directa": 3
}

# ============================================================
# FUNCIONES AUXILIARES
# ============================================================

def normalizar_texto(texto: str) -> str:
    texto = str(texto).strip().lower()
    texto = "".join(
        ch for ch in unicodedata.normalize("NFD", texto)
        if unicodedata.category(ch) != "Mn"
    )
    texto = re.sub(r"[^a-z0-9._-]+", "_", texto)
    return texto

def normalizar_columna(col: str) -> str:
    col = str(col).strip().lower()
    col = "".join(
        ch for ch in unicodedata.normalize("NFD", col)
        if unicodedata.category(ch) != "Mn"
    )
    col = re.sub(r"[^a-z0-9]+", "_", col)
    col = re.sub(r"_+", "_", col).strip("_")
    return col

def normalizar_espacios(texto: str) -> str:
    return re.sub(r"\s+", " ", str(texto)).strip()

def guardar_csv(df: pd.DataFrame, ruta: Path):
    ruta.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(ruta, index=False, encoding="utf-8")

def mostrar_resumen(df: pd.DataFrame, nombre: str, n=5):
    print(f"{nombre}: {df.shape[0]:,} filas × {df.shape[1]:,} columnas")
    display(df.head(n))

def ruta_anio(anio: str) -> Path:
    ruta = RUTA_BRUTOS / anio
    ruta.mkdir(parents=True, exist_ok=True)
    return ruta

def nombre_archivo_estandar(anio: str, tipo_descarga: str, extension=".xlsx") -> str:
    return f"oece_convocatorias_{anio}_{tipo_descarga}{extension}"

def buscar_archivo_existente(anio: str, tipo_descarga: str):
    carpeta = ruta_anio(anio)
    patron = f"oece_convocatorias_{anio}_{tipo_descarga}.*"
    candidatos = sorted(carpeta.glob(patron))
    return candidatos[0] if candidatos else None

# ============================================================
# PLAN DE DESCARGA A PARTIR DEL INVENTARIO RENDERIZADO
# ============================================================

plan_descarga = (
    inventario_botones[
        (inventario_botones["estado"] == "ok") &
        (inventario_botones["tipo_descarga"].notna())
    ]
    .copy()
)

plan_descarga["orden_tipo"] = plan_descarga["tipo_descarga"].map(ORDEN_TIPOS)
plan_descarga = plan_descarga.sort_values(["anio", "orden_tipo", "texto_boton"]).reset_index(drop=True)

plan_descarga["archivo_existente"] = plan_descarga.apply(
    lambda x: str(buscar_archivo_existente(str(x["anio"]), x["tipo_descarga"])) if buscar_archivo_existente(str(x["anio"]), x["tipo_descarga"]) else None,
    axis=1
)

plan_descarga["ya_descargado"] = plan_descarga["archivo_existente"].notna().astype(int)

guardar_csv(plan_descarga, RUTA_META / "tf_p2_plan_descarga_multianual.csv")
mostrar_resumen(plan_descarga, "plan_descarga", n=20)

print("Años incluidos en la ejecución:", sorted(plan_descarga["anio"].astype(str).unique()))
print("Total de combinaciones visibles año × paquete:", len(plan_descarga))

# ============================================================
# INSTALACIÓN DE PAQUETES DE DESCARGA Y AUDITORÍA
# ============================================================

!pip -q install selenium webdriver-manager openpyxl requests beautifulsoup4 lxml
!wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!dpkg -i google-chrome-stable_current_amd64.deb > /dev/null 2>&1 || true
!apt-get -f install -y -qq > /dev/null 2>&1

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

# ============================================================
# DIRECTORIO TEMPORAL DE DESCARGA
# ============================================================

DOWNLOAD_DIR = RUTA_BRUTOS / "_temp_downloads"
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

def limpiar_temporales(download_dir: Path):
    for archivo in download_dir.glob("*.crdownload"):
        try:
            archivo.unlink()
        except Exception:
            pass

def esperar_descarga(download_dir: Path, archivos_antes: set, timeout=180, poll=1):
    inicio = time.time()

    while time.time() - inicio < timeout:
        archivos_actuales = set(download_dir.iterdir())
        nuevos = [p for p in archivos_actuales - archivos_antes if p.is_file()]

        finales = [p for p in nuevos if not p.name.endswith(".crdownload")]
        temporales = [p for p in nuevos if p.name.endswith(".crdownload")]

        if finales and not temporales:
            finales = sorted(finales, key=lambda p: p.stat().st_mtime, reverse=True)
            return finales[0]

        time.sleep(poll)

    return None

def crear_driver_descarga(download_dir: Path):
    opciones = Options()
    opciones.add_argument("--headless")
    opciones.add_argument("--no-sandbox")
    opciones.add_argument("--disable-dev-shm-usage")
    opciones.add_argument("--disable-gpu")
    opciones.add_argument("--window-size=1920,1080")
    opciones.add_argument("--remote-debugging-port=9222")
    opciones.binary_location = "/usr/bin/google-chrome"

    prefs = {
        "download.default_directory": str(download_dir),
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "safebrowsing.enabled": True
    }
    opciones.add_experimental_option("prefs", prefs)

    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=opciones)

    driver.execute_cdp_cmd(
        "Page.setDownloadBehavior",
        {"behavior": "allow", "downloadPath": str(download_dir)}
    )

    driver.maximize_window()
    return driver

def obtener_contenedor_anio(driver, anio: str, max_niveles=10):
    year_xpath = f"//*[normalize-space(text())='{anio}']"
    year_el = driver.find_element(By.XPATH, year_xpath)

    actual = year_el
    for _ in range(max_niveles):
        texto = normalizar_espacios(actual.text).upper()
        botones = actual.find_elements(By.XPATH, ".//button | .//a")
        textos_botones = [
            normalizar_espacios(b.text).upper()
            for b in botones
            if normalizar_espacios(b.text)
        ]

        if "FORMATO EXCEL" in texto and any("DESCARGAR" in tb for tb in textos_botones):
            return actual

        actual = actual.find_element(By.XPATH, "..")

    return None

def encontrar_boton_por_texto(driver, anio: str, texto_objetivo: str):
    contenedor = obtener_contenedor_anio(driver, anio)
    if contenedor is None:
        return None

    botones = contenedor.find_elements(By.XPATH, ".//button | .//a")
    for el in botones:
        texto = normalizar_espacios(el.text)
        if texto.upper() == normalizar_espacios(texto_objetivo).upper():
            return el

    return None

def construir_destino_final(anio: str, tipo_descarga: str, archivo_descargado: Path) -> Path:
    extension = archivo_descargado.suffix.lower() if archivo_descargado.suffix else ".xlsx"
    return ruta_anio(anio) / nombre_archivo_estandar(anio, tipo_descarga, extension)

# ============================================================
# APERTURA DEL DRIVER Y EVIDENCIA RENDERIZADA DE LA PARTE 2
# ============================================================

limpiar_temporales(DOWNLOAD_DIR)

driver = crear_driver_descarga(DOWNLOAD_DIR)
driver.get(URL_CONVOCATORIAS)
time.sleep(7)

html_renderizado_p2 = driver.page_source
texto_renderizado_p2 = driver.find_element(By.TAG_NAME, "body").text

with open(RUTA_HTML / "tf_p2_convocatorias_renderizado_operativo.html", "w", encoding="utf-8") as f:
    f.write(html_renderizado_p2)

with open(RUTA_HTML / "tf_p2_convocatorias_renderizado_operativo.txt", "w", encoding="utf-8") as f:
    f.write(texto_renderizado_p2)

print("Driver inicializado correctamente.")
print("Longitud HTML renderizado operativo:", len(html_renderizado_p2))
print("Directorio temporal de descarga:", DOWNLOAD_DIR)

# ============================================================
# DESCARGA CONTROLADA MULTIANUAL
# ============================================================

registro_descargas = []

for _, fila in plan_descarga.iterrows():
    anio = str(fila["anio"])
    texto_boton = fila["texto_boton"]
    tipo_descarga = fila["tipo_descarga"]

    archivo_existente = buscar_archivo_existente(anio, tipo_descarga)

    # Si ya existe y no queremos reemplazar, registramos y seguimos
    if (archivo_existente is not None) and (REEMPLAZAR_DESCARGAS is False):
        registro_descargas.append({
            "anio": anio,
            "texto_boton": texto_boton,
            "tipo_descarga": tipo_descarga,
            "estado_descarga": "ya_existia",
            "archivo_guardado": str(archivo_existente),
            "archivo_nombre": archivo_existente.name,
            "extension": archivo_existente.suffix.lower(),
            "tamano_bytes": archivo_existente.stat().st_size,
            "error": None
        })
        print(f"· Ya existía: {archivo_existente.name}")
        continue

    try:
        boton = encontrar_boton_por_texto(driver, anio, texto_boton)

        if boton is None:
            raise ValueError(f"No se pudo re-localizar el botón '{texto_boton}' para el año {anio}")

        archivos_antes = set(DOWNLOAD_DIR.iterdir())

        driver.execute_script("arguments[0].scrollIntoView({block:'center'});", boton)
        time.sleep(1)
        driver.execute_script("arguments[0].click();", boton)

        archivo_descargado = esperar_descarga(DOWNLOAD_DIR, archivos_antes, timeout=180, poll=1)

        if archivo_descargado is None:
            raise TimeoutError("No se detectó archivo descargado dentro del tiempo esperado.")

        destino = construir_destino_final(anio, tipo_descarga, archivo_descargado)

        if destino.exists():
            destino.unlink()

        shutil.move(str(archivo_descargado), str(destino))

        registro_descargas.append({
            "anio": anio,
            "texto_boton": texto_boton,
            "tipo_descarga": tipo_descarga,
            "estado_descarga": "descargado",
            "archivo_guardado": str(destino),
            "archivo_nombre": destino.name,
            "extension": destino.suffix.lower(),
            "tamano_bytes": destino.stat().st_size,
            "error": None
        })

        print(f"✓ Descargado: {destino.name}")
        time.sleep(2)

    except Exception as e:
        registro_descargas.append({
            "anio": anio,
            "texto_boton": texto_boton,
            "tipo_descarga": tipo_descarga,
            "estado_descarga": "error",
            "archivo_guardado": None,
            "archivo_nombre": None,
            "extension": None,
            "tamano_bytes": None,
            "error": str(e)
        })
        print(f"✗ Error en {anio} | {tipo_descarga}: {e}")

df_registro_descargas = pd.DataFrame(registro_descargas)
guardar_csv(df_registro_descargas, RUTA_LOGS / "tf_p2_registro_descargas.csv")
mostrar_resumen(df_registro_descargas, "df_registro_descargas", n=30)

# ============================================================
# CIERRE DEL DRIVER
# ============================================================

driver.quit()
print("Driver cerrado correctamente.")

# ============================================================
# INVENTARIO FÍSICO DE ARCHIVOS DESCARGADOS
# ============================================================

archivos_descargados = []

for subcarpeta in sorted(RUTA_BRUTOS.iterdir()):
    if not subcarpeta.is_dir():
        continue
    if subcarpeta.name.startswith("_"):
        continue
    if not re.fullmatch(r"\d{4}", subcarpeta.name):
        continue

    anio = subcarpeta.name

    for archivo in sorted(subcarpeta.glob("*")):
        if archivo.is_file():
            archivos_descargados.append({
                "anio": anio,
                "archivo": archivo.name,
                "ruta": str(archivo),
                "extension": archivo.suffix.lower(),
                "tamano_bytes": archivo.stat().st_size,
                "tamano_mb": round(archivo.stat().st_size / (1024**2), 3),
                "existe": 1
            })

df_archivos_descargados = pd.DataFrame(archivos_descargados)

guardar_csv(df_archivos_descargados, RUTA_RESULTADOS_TABLAS / "tf_p2_inventario_fisico_descargas.csv")
mostrar_resumen(df_archivos_descargados, "df_archivos_descargados", n=30)

print("Total de archivos físicos encontrados:", len(df_archivos_descargados))

# ============================================================
# ACTUALIZACIÓN DEL MANIFEST CON ESTADO DE DESCARGA
# ============================================================

manifest_descarga = manifest_inicial.copy()

manifest_descarga["anio"] = manifest_descarga["anio"].astype(str)
manifest_descarga["estado_descarga_final"] = "pendiente"
manifest_descarga["archivo_encontrado"] = None
manifest_descarga["ruta_archivo"] = None
manifest_descarga["extension_real"] = None
manifest_descarga["tamano_bytes"] = np.nan

if not df_archivos_descargados.empty:
    for idx, row in manifest_descarga.iterrows():
        anio = str(row["anio"])
        tipo = row["tipo_descarga"]

        match = df_archivos_descargados[
            (df_archivos_descargados["anio"] == anio) &
            (df_archivos_descargados["archivo"].str.contains(tipo, na=False))
        ]

        if not match.empty:
            manifest_descarga.loc[idx, "estado_descarga_final"] = "ok"
            manifest_descarga.loc[idx, "archivo_encontrado"] = match.iloc[0]["archivo"]
            manifest_descarga.loc[idx, "ruta_archivo"] = match.iloc[0]["ruta"]
            manifest_descarga.loc[idx, "extension_real"] = match.iloc[0]["extension"]
            manifest_descarga.loc[idx, "tamano_bytes"] = match.iloc[0]["tamano_bytes"]
        else:
            if int(row.get("visible_en_render", 0)) == 1:
                manifest_descarga.loc[idx, "estado_descarga_final"] = "faltante"
            else:
                manifest_descarga.loc[idx, "estado_descarga_final"] = "no_visible_en_render"

guardar_csv(manifest_descarga, RUTA_ADMIN / "manifest_descarga_actualizado.csv")
mostrar_resumen(manifest_descarga, "manifest_descarga", n=20)

# ============================================================
# AUDITORÍA TÉCNICA DE EXCEL
# ============================================================

from openpyxl import load_workbook

def inferir_tipo_descarga_desde_nombre(nombre_archivo: str) -> str:
    nombre = normalizar_texto(nombre_archivo)

    if "todos_los_procesos" in nombre:
        return "todos_los_procesos"
    elif "subasta_inversa" in nombre:
        return "solo_subasta_inversa_electronica"
    elif "contratacion_directa" in nombre:
        return "solo_contratacion_directa"
    else:
        return "tipo_no_identificado"

def leer_encabezados_primera_hoja(ruta_archivo: Path, nrows=5):
    try:
        df_head = pd.read_excel(ruta_archivo, sheet_name=0, nrows=nrows)
        return list(df_head.columns)
    except Exception:
        return []

def auditar_excel_un_archivo(ruta_archivo: Path):
    auditoria_hojas = []
    columnas_primera_hoja = []

    anio = re.search(r"20\d{2}", ruta_archivo.name).group(0) if re.search(r"20\d{2}", ruta_archivo.name) else None
    tipo_descarga = inferir_tipo_descarga_desde_nombre(ruta_archivo.name)

    try:
        wb = load_workbook(ruta_archivo, read_only=True, data_only=True)
        hojas = wb.sheetnames

        for hoja in hojas:
            ws = wb[hoja]
            n_filas = ws.max_row
            n_columnas = ws.max_column

            auditoria_hojas.append({
                "archivo": ruta_archivo.name,
                "anio": anio,
                "tipo_descarga": tipo_descarga,
                "hoja": hoja,
                "n_filas_aprox": n_filas,
                "n_columnas_aprox": n_columnas,
                "estado_auditoria": "ok"
            })

        encabezados = leer_encabezados_primera_hoja(ruta_archivo)

        for i, col in enumerate(encabezados, start=1):
            columnas_primera_hoja.append({
                "archivo": ruta_archivo.name,
                "anio": anio,
                "tipo_descarga": tipo_descarga,
                "hoja": hojas[0] if hojas else None,
                "orden_columna": i,
                "columna": col,
                "columna_normalizada": normalizar_columna(col)
            })

        resumen_archivo = {
            "archivo": ruta_archivo.name,
            "anio": anio,
            "tipo_descarga": tipo_descarga,
            "ruta": str(ruta_archivo),
            "legible": 1,
            "n_hojas": len(hojas),
            "n_filas_aprox_max": max([x["n_filas_aprox"] for x in auditoria_hojas]) if auditoria_hojas else np.nan,
            "n_columnas_aprox_max": max([x["n_columnas_aprox"] for x in auditoria_hojas]) if auditoria_hojas else np.nan,
            "n_columnas_primera_hoja": len(encabezados),
            "tamano_bytes": ruta_archivo.stat().st_size,
            "tamano_mb": round(ruta_archivo.stat().st_size / (1024**2), 3),
            "estado_auditoria": "ok",
            "error": None
        }

    except Exception as e:
        resumen_archivo = {
            "archivo": ruta_archivo.name,
            "anio": anio,
            "tipo_descarga": tipo_descarga,
            "ruta": str(ruta_archivo),
            "legible": 0,
            "n_hojas": np.nan,
            "n_filas_aprox_max": np.nan,
            "n_columnas_aprox_max": np.nan,
            "n_columnas_primera_hoja": np.nan,
            "tamano_bytes": ruta_archivo.stat().st_size if ruta_archivo.exists() else np.nan,
            "tamano_mb": round(ruta_archivo.stat().st_size / (1024**2), 3) if ruta_archivo.exists() else np.nan,
            "estado_auditoria": "error",
            "error": str(e)
        }

    return auditoria_hojas, columnas_primera_hoja, resumen_archivo


auditoria_hojas_total = []
columnas_total = []
resumen_archivos_total = []

for _, fila in df_archivos_descargados.iterrows():
    ruta_archivo = Path(fila["ruta"])

    if not ruta_archivo.exists():
        resumen_archivos_total.append({
            "archivo": fila["archivo"],
            "anio": fila["anio"],
            "tipo_descarga": inferir_tipo_descarga_desde_nombre(fila["archivo"]),
            "ruta": str(ruta_archivo),
            "legible": 0,
            "n_hojas": np.nan,
            "n_filas_aprox_max": np.nan,
            "n_columnas_aprox_max": np.nan,
            "n_columnas_primera_hoja": np.nan,
            "tamano_bytes": np.nan,
            "tamano_mb": np.nan,
            "estado_auditoria": "archivo_no_encontrado",
            "error": "archivo_no_encontrado"
        })
        continue

    auditoria_hojas, columnas_primera_hoja, resumen_archivo = auditar_excel_un_archivo(ruta_archivo)

    auditoria_hojas_total.extend(auditoria_hojas)
    columnas_total.extend(columnas_primera_hoja)
    resumen_archivos_total.append(resumen_archivo)

df_auditoria_excel = pd.DataFrame(auditoria_hojas_total)
df_columnas_excel = pd.DataFrame(columnas_total)
df_resumen_archivos = pd.DataFrame(resumen_archivos_total)

guardar_csv(df_resumen_archivos, RUTA_AUDITORIAS / "tf_p2_resumen_archivos.csv")

if not df_auditoria_excel.empty:
    guardar_csv(df_auditoria_excel, RUTA_AUDITORIAS / "tf_p2_auditoria_excel.csv")

if not df_columnas_excel.empty:
    guardar_csv(df_columnas_excel, RUTA_AUDITORIAS / "tf_p2_columnas_excel.csv")

mostrar_resumen(df_resumen_archivos, "df_resumen_archivos", n=30)

if not df_auditoria_excel.empty:
    mostrar_resumen(df_auditoria_excel, "df_auditoria_excel", n=20)

if not df_columnas_excel.empty:
    mostrar_resumen(df_columnas_excel, "df_columnas_excel", n=20)

# ============================================================
# RESUMEN TÉCNICO POR AÑO Y TIPO
# ============================================================

if not df_resumen_archivos.empty:
    resumen_tecnico = (
        df_resumen_archivos
        .groupby(["anio", "tipo_descarga"], as_index=False)
        .agg(
            n_archivos=("archivo", "count"),
            n_legibles=("legible", "sum"),
            n_hojas_prom=("n_hojas", "mean"),
            n_filas_aprox_max=("n_filas_aprox_max", "max"),
            n_columnas_aprox_max=("n_columnas_aprox_max", "max"),
            tamano_total_mb=("tamano_mb", "sum")
        )
        .sort_values(["anio", "tipo_descarga"])
    )

    guardar_csv(resumen_tecnico, RUTA_RESULTADOS_RESUMENES / "tf_p2_resumen_tecnico_por_anio_tipo.csv")
    mostrar_resumen(resumen_tecnico, "resumen_tecnico", n=30)

# ============================================================
# COMPARACIÓN ESTRUCTURAL DE COLUMNAS POR AÑO Y TIPO
# ============================================================

if not df_columnas_excel.empty:
    comparacion_columnas = (
        df_columnas_excel
        .groupby(["anio", "tipo_descarga"])["columna_normalizada"]
        .apply(list)
        .reset_index()
    )

    guardar_csv(comparacion_columnas, RUTA_RESULTADOS_RESUMENES / "tf_p2_comparacion_columnas_por_anio_tipo.csv")
    mostrar_resumen(comparacion_columnas, "comparacion_columnas", n=20)

# ============================================================
# CONSISTENCIA ESTRUCTURAL ENTRE AÑOS POR TIPO
# ============================================================

consistencia_estructural = []

if not df_columnas_excel.empty:
    for tipo in df_columnas_excel["tipo_descarga"].dropna().unique():
        sub = df_columnas_excel[df_columnas_excel["tipo_descarga"] == tipo].copy()

        estructura_por_anio = (
            sub.groupby("anio")["columna_normalizada"]
            .apply(lambda x: tuple(sorted(set(x))))
            .to_dict()
        )

        anios_tipo = sorted(estructura_por_anio.keys())
        estructura_referencia = None
        consistencia_total = 1

        if anios_tipo:
            estructura_referencia = estructura_por_anio[anios_tipo[0]]

            for anio in anios_tipo[1:]:
                if estructura_por_anio[anio] != estructura_referencia:
                    consistencia_total = 0
                    break

        consistencia_estructural.append({
            "tipo_descarga": tipo,
            "n_anios_observados": len(anios_tipo),
            "estructura_consistente_entre_anios": consistencia_total
        })

df_consistencia_estructural = pd.DataFrame(consistencia_estructural)
guardar_csv(df_consistencia_estructural, RUTA_RESULTADOS_RESUMENES / "tf_p2_consistencia_estructural.csv")
mostrar_resumen(df_consistencia_estructural, "df_consistencia_estructural", n=10)

# ============================================================
# ACTUALIZACIÓN FINAL DEL MANIFEST CON AUDITORÍA
# ============================================================

manifest_auditoria = manifest_descarga.copy()

manifest_auditoria["estado_auditoria_final"] = "pendiente"
manifest_auditoria["archivo_legible"] = 0
manifest_auditoria["n_hojas"] = np.nan
manifest_auditoria["n_filas_aprox_max"] = np.nan
manifest_auditoria["n_columnas_aprox_max"] = np.nan

if not df_resumen_archivos.empty:
    for idx, row in manifest_auditoria.iterrows():
        anio = str(row["anio"])
        tipo = row["tipo_descarga"]

        match = df_resumen_archivos[
            (df_resumen_archivos["anio"].astype(str) == anio) &
            (df_resumen_archivos["tipo_descarga"] == tipo)
        ]

        if not match.empty:
            manifest_auditoria.loc[idx, "estado_auditoria_final"] = match.iloc[0]["estado_auditoria"]
            manifest_auditoria.loc[idx, "archivo_legible"] = int(match.iloc[0]["legible"])
            manifest_auditoria.loc[idx, "n_hojas"] = match.iloc[0]["n_hojas"]
            manifest_auditoria.loc[idx, "n_filas_aprox_max"] = match.iloc[0]["n_filas_aprox_max"]
            manifest_auditoria.loc[idx, "n_columnas_aprox_max"] = match.iloc[0]["n_columnas_aprox_max"]
        else:
            if manifest_auditoria.loc[idx, "estado_descarga_final"] == "ok":
                manifest_auditoria.loc[idx, "estado_auditoria_final"] = "sin_resumen"
            else:
                manifest_auditoria.loc[idx, "estado_auditoria_final"] = "no_aplica"

guardar_csv(manifest_auditoria, RUTA_ADMIN / "manifest_auditoria_actualizado.csv")
mostrar_resumen(manifest_auditoria, "manifest_auditoria", n=20)

# ============================================================
# BITÁCORA METODOLÓGICA DE LA PARTE 2/3
# ============================================================

bitacora_p2 = pd.DataFrame([
    {
        "paso": 1,
        "descripcion": "Carga y validación de artefactos producidos en la Parte 1/1",
        "salida_principal": "Manifest inicial e inventario renderizado"
    },
    {
        "paso": 2,
        "descripcion": "Construcción del plan de descarga multianual total",
        "salida_principal": "Plan de ejecución por año y tipo"
    },
    {
        "paso": 3,
        "descripcion": "Configuración de Selenium con permiso explícito de descarga",
        "salida_principal": "Driver operativo y evidencia renderizada"
    },
    {
        "paso": 4,
        "descripcion": "Descarga controlada, renombrado y registro de eventos",
        "salida_principal": "Registro de descargas"
    },
    {
        "paso": 5,
        "descripcion": "Inventario físico de archivos descargados",
        "salida_principal": "Tabla de archivos físicos"
    },
    {
        "paso": 6,
        "descripcion": "Auditoría técnica de archivos Excel",
        "salida_principal": "Resumen técnico, hojas y columnas"
    },
    {
        "paso": 7,
        "descripcion": "Actualización del manifest con estados de descarga y auditoría",
        "salida_principal": "Manifest auditado"
    }
])

guardar_csv(bitacora_p2, RUTA_LOGS / "tf_p2_bitacora_metodologica.csv")
mostrar_resumen(bitacora_p2, "bitacora_p2", n=10)

print("Parte 2/3 completada correctamente.")

print("\nArchivos clave generados:")
print("-", RUTA_LOGS / "tf_p2_registro_descargas.csv")
print("-", RUTA_RESULTADOS_TABLAS / "tf_p2_inventario_fisico_descargas.csv")
print("-", RUTA_AUDITORIAS / "tf_p2_resumen_archivos.csv")
print("-", RUTA_AUDITORIAS / "tf_p2_auditoria_excel.csv")
print("-", RUTA_AUDITORIAS / "tf_p2_columnas_excel.csv")
print("-", RUTA_ADMIN / "manifest_descarga_actualizado.csv")
print("-", RUTA_ADMIN / "manifest_auditoria_actualizado.csv")

"""# Trabajo Final — Parte 3/3
# Lectura multianual, ensamblaje final, visualización y cierre metodológico

## Propósito de esta parte
Esta tercera parte transforma los archivos descargados y auditados en la Parte 2/3 en una base administrativa multianual legible, comparable y analíticamente utilizable. Su objetivo no es producir inferencias causales ni agotar sustantivamente el universo de las contrataciones públicas, sino cerrar el workflow reproducible mediante lectura, normalización, ensamblaje, construcción de una base principal y generación de outputs descriptivos claros, exportables y presentables.

## Decisión analítica central
Los paquetes descargados no deben sumarse mecánicamente como si fueran universos independientes. Para evitar duplicación conceptual y empírica:

- la base **principal** de análisis será el paquete **todos_los_procesos**;
- los paquetes **solo_subasta_inversa_electronica** y **solo_contratacion_directa** serán tratados como subconjuntos comparativos.

## Secuencia metodológica
**archivos auditados → lectura multianual → base comparativa → base principal → tabla limpia → tablas resumen → visualización → exportación final**

## Resultado esperado
Al finalizar esta parte, el Trabajo Final debe contar con:
- una base comparativa multianual;
- una base principal multianual;
- una tabla limpia de trabajo;
- tablas y gráficos exploratorios exportados;
- manifest final de ensamblaje;
- bitácora metodológica de cierre.
"""

from pathlib import Path
import pandas as pd
import numpy as np
import re
import unicodedata
import json
import matplotlib.pyplot as plt
from collections import Counter

pd.set_option("display.max_columns", 250)
pd.set_option("display.width", 260)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# RUTAS BASE DEL PROYECTO
# ============================================================

BASE = Path("/content/drive/MyDrive/IA Generativa para CCSS/Trabajo Final")

RUTA_ADMIN = BASE / "00_admin"
RUTA_FUENTE = BASE / "02_fuente_web"
RUTA_BRUTOS = BASE / "03_datos_brutos" / "convocatorias"

RUTA_PROCESADOS = BASE / "04_datos_procesados"
RUTA_AUDITORIAS = RUTA_PROCESADOS / "auditorias"
RUTA_TABLAS_LIMPIAS = RUTA_PROCESADOS / "tablas_limpias"
RUTA_TABLAS_UNIFICADAS = RUTA_PROCESADOS / "tablas_unificadas"
RUTA_VARIABLES = RUTA_PROCESADOS / "variables_derivadas"

RUTA_RESULTADOS = BASE / "07_resultados"
RUTA_RESULTADOS_TABLAS = RUTA_RESULTADOS / "tablas"
RUTA_RESULTADOS_FIGURAS = RUTA_RESULTADOS / "figuras"
RUTA_RESULTADOS_RESUMENES = RUTA_RESULTADOS / "resumenes"

for ruta in [
    RUTA_ADMIN, RUTA_BRUTOS, RUTA_PROCESADOS, RUTA_AUDITORIAS,
    RUTA_TABLAS_LIMPIAS, RUTA_TABLAS_UNIFICADAS, RUTA_VARIABLES,
    RUTA_RESULTADOS, RUTA_RESULTADOS_TABLAS, RUTA_RESULTADOS_FIGURAS,
    RUTA_RESULTADOS_RESUMENES
]:
    ruta.mkdir(parents=True, exist_ok=True)

# ============================================================
# ARCHIVOS CLAVE PRODUCIDOS EN LAS PARTES ANTERIORES
# ============================================================

RUTA_MANIFEST_AUDITORIA = RUTA_ADMIN / "manifest_auditoria_actualizado.csv"
RUTA_RESUMEN_ARCHIVOS = RUTA_AUDITORIAS / "tf_p2_resumen_archivos.csv"
RUTA_AUDITORIA_EXCEL = RUTA_AUDITORIAS / "tf_p2_auditoria_excel.csv"
RUTA_COLUMNAS_EXCEL = RUTA_AUDITORIAS / "tf_p2_columnas_excel.csv"

for ruta in [RUTA_MANIFEST_AUDITORIA, RUTA_RESUMEN_ARCHIVOS]:
    if not ruta.exists():
        raise FileNotFoundError(f"No existe el archivo requerido: {ruta}")

manifest_auditoria = pd.read_csv(RUTA_MANIFEST_AUDITORIA)
df_resumen_archivos = pd.read_csv(RUTA_RESUMEN_ARCHIVOS)

if RUTA_AUDITORIA_EXCEL.exists():
    df_auditoria_excel = pd.read_csv(RUTA_AUDITORIA_EXCEL)
else:
    df_auditoria_excel = pd.DataFrame()

if RUTA_COLUMNAS_EXCEL.exists():
    df_columnas_excel = pd.read_csv(RUTA_COLUMNAS_EXCEL)
else:
    df_columnas_excel = pd.DataFrame()

manifest_auditoria["anio"] = manifest_auditoria["anio"].astype(str)
df_resumen_archivos["anio"] = df_resumen_archivos["anio"].astype(str)

print("Artefactos de entrada cargados correctamente.")
print("manifest_auditoria:", manifest_auditoria.shape)
print("df_resumen_archivos:", df_resumen_archivos.shape)
print("df_auditoria_excel:", df_auditoria_excel.shape)
print("df_columnas_excel:", df_columnas_excel.shape)

display(manifest_auditoria.head())
display(df_resumen_archivos.head())

# ============================================================
# FUNCIONES AUXILIARES
# ============================================================

def normalizar_texto(texto: str) -> str:
    texto = str(texto).strip().lower()
    texto = "".join(
        ch for ch in unicodedata.normalize("NFD", texto)
        if unicodedata.category(ch) != "Mn"
    )
    texto = re.sub(r"[^a-z0-9._-]+", "_", texto)
    return texto

def normalizar_columna(col: str) -> str:
    col = str(col).strip().lower()
    col = "".join(
        ch for ch in unicodedata.normalize("NFD", col)
        if unicodedata.category(ch) != "Mn"
    )
    col = re.sub(r"[^a-z0-9]+", "_", col)
    col = re.sub(r"_+", "_", col).strip("_")
    return col

def guardar_csv(df: pd.DataFrame, ruta: Path):
    ruta.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(ruta, index=False, encoding="utf-8")

def mostrar_resumen(df: pd.DataFrame, nombre: str, n=5):
    print(f"{nombre}: {df.shape[0]:,} filas × {df.shape[1]:,} columnas")
    display(df.head(n))

def buscar_columna_por_fragmentos(columnas, patrones):
    cols_norm = {c: normalizar_columna(c) for c in columnas}

    for patron in patrones:
        patron_norm = normalizar_columna(patron)

        for col_original, col_norm in cols_norm.items():
            if col_norm == patron_norm:
                return col_original

        for col_original, col_norm in cols_norm.items():
            if patron_norm in col_norm:
                return col_original

    return None

def convertir_monto_robusto(serie):
    s = serie.astype(str).str.strip()
    s = s.replace({"nan": np.nan, "None": np.nan, "": np.nan})
    s = s.str.replace(",", "", regex=False)
    s = s.str.replace(" ", "", regex=False)
    return pd.to_numeric(s, errors="coerce")

def limpiar_texto_basico(texto):
    if pd.isna(texto):
        return ""
    texto = str(texto).lower()
    texto = "".join(
        ch for ch in unicodedata.normalize("NFD", texto)
        if unicodedata.category(ch) != "Mn"
    )
    texto = re.sub(r"[^a-z0-9\s]", " ", texto)
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto

def auditar_dataframe(df: pd.DataFrame, nombre: str) -> pd.DataFrame:
    resumen = pd.DataFrame({
        "variable": df.columns,
        "dtype": df.dtypes.astype(str).values,
        "n_missing": df.isna().sum().values,
        "pct_missing": (df.isna().mean() * 100).round(2).values,
        "n_unicos": df.nunique(dropna=True).values
    })
    print(f"{nombre}: {df.shape[0]:,} filas × {df.shape[1]:,} columnas")
    return resumen.sort_values(["pct_missing", "variable"], ascending=[False, True]).reset_index(drop=True)

def cargar_paquete_oece_multianual(ruta_archivo: Path, anio: str, tipo_descarga: str) -> pd.DataFrame:
    df = pd.read_excel(ruta_archivo, sheet_name=0)
    df.columns = [normalizar_columna(c) for c in df.columns]
    df["anio"] = str(anio)
    df["tipo_descarga"] = tipo_descarga
    df["archivo_origen"] = ruta_archivo.name
    df["ruta_origen"] = str(ruta_archivo)
    return df

# ============================================================
# FILTRADO DE ARCHIVOS LEGIBLES
# ============================================================

df_archivos_legibles = df_resumen_archivos[
    (df_resumen_archivos["estado_auditoria"] == "ok") &
    (df_resumen_archivos["legible"] == 1)
].copy()

if df_archivos_legibles.empty:
    raise ValueError("No hay archivos legibles disponibles para la Parte 3/3.")

mostrar_resumen(df_archivos_legibles, "df_archivos_legibles", n=20)

# ============================================================
# LECTURA MULTIANUAL DE ARCHIVOS AUDITADOS
# ============================================================

bases_cargadas = []
registro_lectura = []

for _, fila in df_archivos_legibles.iterrows():
    ruta_archivo = Path(fila["ruta"])
    anio = str(fila["anio"])
    tipo_descarga = fila["tipo_descarga"]

    try:
        df_tmp = cargar_paquete_oece_multianual(ruta_archivo, anio, tipo_descarga)

        bases_cargadas.append(df_tmp)

        registro_lectura.append({
            "archivo": ruta_archivo.name,
            "anio": anio,
            "tipo_descarga": tipo_descarga,
            "estado_lectura": "ok",
            "n_filas": len(df_tmp),
            "n_columnas": df_tmp.shape[1]
        })

    except Exception as e:
        registro_lectura.append({
            "archivo": ruta_archivo.name,
            "anio": anio,
            "tipo_descarga": tipo_descarga,
            "estado_lectura": "error",
            "n_filas": np.nan,
            "n_columnas": np.nan,
            "error": str(e)
        })

df_registro_lectura = pd.DataFrame(registro_lectura)
guardar_csv(df_registro_lectura, RUTA_AUDITORIAS / "tf_p3_registro_lectura.csv")
mostrar_resumen(df_registro_lectura, "df_registro_lectura", n=30)

if not bases_cargadas:
    raise ValueError("No se pudo cargar ninguna base auditada.")

base_paquetes_multianual = pd.concat(bases_cargadas, ignore_index=True)

guardar_csv(base_paquetes_multianual, RUTA_TABLAS_UNIFICADAS / "tf_p3_base_paquetes_multianual_raw.csv")
mostrar_resumen(base_paquetes_multianual, "base_paquetes_multianual", n=10)

# ============================================================
# ESTRUCTURA DE PAQUETES MULTIANUAL
# ============================================================

estructura_paquetes = (
    base_paquetes_multianual
    .groupby("tipo_descarga", as_index=False)
    .agg(
        n_registros=("tipo_descarga", "count"),
        n_anios=("anio", "nunique"),
        n_archivos=("archivo_origen", "nunique")
    )
    .sort_values("tipo_descarga")
)

guardar_csv(estructura_paquetes, RUTA_RESULTADOS_RESUMENES / "tf_p3_estructura_paquetes.csv")
mostrar_resumen(estructura_paquetes, "estructura_paquetes", n=10)

# ============================================================
# DECISIÓN ANALÍTICA CENTRAL
# ============================================================

PAQUETE_PRINCIPAL = "todos_los_procesos"

base_principal_multianual = base_paquetes_multianual[
    base_paquetes_multianual["tipo_descarga"] == PAQUETE_PRINCIPAL
].copy()

base_subasta_multianual = base_paquetes_multianual[
    base_paquetes_multianual["tipo_descarga"] == "solo_subasta_inversa_electronica"
].copy()

base_contratacion_directa_multianual = base_paquetes_multianual[
    base_paquetes_multianual["tipo_descarga"] == "solo_contratacion_directa"
].copy()

print("Dimensiones de objetos analíticos:")
print("base_principal_multianual            :", base_principal_multianual.shape)
print("base_subasta_multianual              :", base_subasta_multianual.shape)
print("base_contratacion_directa_multianual :", base_contratacion_directa_multianual.shape)

guardar_csv(base_principal_multianual, RUTA_TABLAS_UNIFICADAS / "tf_p3_base_principal_multianual_raw.csv")
guardar_csv(base_subasta_multianual, RUTA_TABLAS_UNIFICADAS / "tf_p3_base_subasta_multianual_raw.csv")
guardar_csv(base_contratacion_directa_multianual, RUTA_TABLAS_UNIFICADAS / "tf_p3_base_contratacion_directa_multianual_raw.csv")

# ============================================================
# AUDITORÍA DE LA BASE PRINCIPAL
# ============================================================

aud_base_principal = auditar_dataframe(base_principal_multianual, "base_principal_multianual")
guardar_csv(aud_base_principal, RUTA_AUDITORIAS / "tf_p3_auditoria_base_principal_multianual.csv")
display(aud_base_principal.head(30))

# ============================================================
# IDENTIFICACIÓN SEMIAUTOMÁTICA DE VARIABLES CLAVE
# ============================================================

col_codigo_entidad = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["codigoentidad"])
col_entidad = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["entidad"])
col_tipo_entidad = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["tipoentidad"])
col_codigo_conv = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["codigoconvocatoria"])
col_desc_proceso = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["descripcion_proceso"])
col_tipo_compra = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["tipocompra"])
col_objeto = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["objetocontractual"])
col_tipo_proceso = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["tipoprocesoseleccion"])
col_sistema = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["sistema_contratacion"])
col_monto = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["montoreferencial"])
col_moneda = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["moneda"])
col_dep = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["departamento_item"])
col_prov = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["provincia_item"])
col_dist = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["distrito_item"])
col_fecha_conv = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["fecha_convocatoria"])
col_fecha_bases = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["fechaintegracionbases"])
col_fecha_prop = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["fechapresentacionpropuesta"])
col_desc_item = buscar_columna_por_fragmentos(base_principal_multianual.columns, ["descripcion_item"])

variables_detectadas = pd.DataFrame([
    {"variable_logica": "codigo_entidad", "columna_detectada": col_codigo_entidad},
    {"variable_logica": "entidad", "columna_detectada": col_entidad},
    {"variable_logica": "tipo_entidad", "columna_detectada": col_tipo_entidad},
    {"variable_logica": "codigo_convocatoria", "columna_detectada": col_codigo_conv},
    {"variable_logica": "descripcion_proceso", "columna_detectada": col_desc_proceso},
    {"variable_logica": "tipo_compra", "columna_detectada": col_tipo_compra},
    {"variable_logica": "objeto_contractual", "columna_detectada": col_objeto},
    {"variable_logica": "tipo_proceso", "columna_detectada": col_tipo_proceso},
    {"variable_logica": "sistema_contratacion", "columna_detectada": col_sistema},
    {"variable_logica": "monto_referencial", "columna_detectada": col_monto},
    {"variable_logica": "moneda", "columna_detectada": col_moneda},
    {"variable_logica": "departamento_item", "columna_detectada": col_dep},
    {"variable_logica": "provincia_item", "columna_detectada": col_prov},
    {"variable_logica": "distrito_item", "columna_detectada": col_dist},
    {"variable_logica": "fecha_convocatoria", "columna_detectada": col_fecha_conv},
    {"variable_logica": "fecha_integracion_bases", "columna_detectada": col_fecha_bases},
    {"variable_logica": "fecha_presentacion_propuesta", "columna_detectada": col_fecha_prop},
    {"variable_logica": "descripcion_item", "columna_detectada": col_desc_item},
])

guardar_csv(variables_detectadas, RUTA_VARIABLES / "tf_p3_variables_detectadas_multianual.csv")
mostrar_resumen(variables_detectadas, "variables_detectadas", n=20)

# ============================================================
# CONSTRUCCIÓN DE LA TABLA LIMPIA DE TRABAJO
# ============================================================

columnas_trabajo = {
    "codigo_entidad": col_codigo_entidad,
    "entidad": col_entidad,
    "tipo_entidad": col_tipo_entidad,
    "codigo_convocatoria": col_codigo_conv,
    "descripcion_proceso": col_desc_proceso,
    "tipo_compra": col_tipo_compra,
    "objeto_contractual": col_objeto,
    "tipo_proceso": col_tipo_proceso,
    "sistema_contratacion": col_sistema,
    "monto_referencial": col_monto,
    "moneda": col_moneda,
    "departamento_item": col_dep,
    "provincia_item": col_prov,
    "distrito_item": col_dist,
    "fecha_convocatoria": col_fecha_conv,
    "fecha_integracion_bases": col_fecha_bases,
    "fecha_presentacion_propuesta": col_fecha_prop,
    "descripcion_item": col_desc_item,
    "anio": "anio",
    "tipo_descarga": "tipo_descarga",
    "archivo_origen": "archivo_origen"
}

columnas_existentes = {
    k: v for k, v in columnas_trabajo.items()
    if v is not None and v in base_principal_multianual.columns
}

base_trabajo_multianual = base_principal_multianual[[v for v in columnas_existentes.values()]].copy()
base_trabajo_multianual = base_trabajo_multianual.rename(columns={v: k for k, v in columnas_existentes.items()})

# ============================================================
# VARIABLES DERIVADAS
# ============================================================

if "monto_referencial" in base_trabajo_multianual.columns:
    base_trabajo_multianual["monto_referencial_num"] = convertir_monto_robusto(base_trabajo_multianual["monto_referencial"])

if "fecha_convocatoria" in base_trabajo_multianual.columns:
    base_trabajo_multianual["fecha_convocatoria_dt"] = pd.to_datetime(
        base_trabajo_multianual["fecha_convocatoria"], errors="coerce"
    )
    base_trabajo_multianual["mes_convocatoria"] = (
        base_trabajo_multianual["fecha_convocatoria_dt"]
        .dt.to_period("M")
        .astype("string")
    )

if "descripcion_proceso" in base_trabajo_multianual.columns:
    base_trabajo_multianual["descripcion_proceso_limpia"] = (
        base_trabajo_multianual["descripcion_proceso"].apply(limpiar_texto_basico)
    )
    base_trabajo_multianual["n_caracteres_descripcion"] = (
        base_trabajo_multianual["descripcion_proceso"].astype(str).str.len()
    )

if "codigo_convocatoria" in base_trabajo_multianual.columns:
    base_trabajo_multianual["llave_convocatoria"] = (
        base_trabajo_multianual["codigo_convocatoria"].astype(str).str.strip()
    )
else:
    base_trabajo_multianual["llave_convocatoria"] = (
        base_trabajo_multianual.get("entidad", "").astype(str) + " | " +
        base_trabajo_multianual.get("descripcion_proceso", "").astype(str) + " | " +
        base_trabajo_multianual.get("fecha_convocatoria", "").astype(str)
    )

guardar_csv(base_trabajo_multianual, RUTA_TABLAS_LIMPIAS / "tf_p3_base_trabajo_multianual.csv")
mostrar_resumen(base_trabajo_multianual, "base_trabajo_multianual", n=10)

# ============================================================
# RESUMEN GENERAL DE LA BASE PRINCIPAL MULTIANUAL
# ============================================================

resumen_general_multianual = {
    "n_registros": len(base_trabajo_multianual),
    "n_convocatorias_unicas": base_trabajo_multianual["llave_convocatoria"].nunique(dropna=True),
    "n_entidades_unicas": base_trabajo_multianual["entidad"].nunique(dropna=True) if "entidad" in base_trabajo_multianual.columns else np.nan,
    "n_anios_unicos": base_trabajo_multianual["anio"].nunique(dropna=True) if "anio" in base_trabajo_multianual.columns else np.nan,
    "n_departamentos_unicos": base_trabajo_multianual["departamento_item"].nunique(dropna=True) if "departamento_item" in base_trabajo_multianual.columns else np.nan,
    "pct_con_monto": base_trabajo_multianual["monto_referencial_num"].notna().mean() * 100 if "monto_referencial_num" in base_trabajo_multianual.columns else np.nan,
    "monto_promedio": base_trabajo_multianual["monto_referencial_num"].mean() if "monto_referencial_num" in base_trabajo_multianual.columns else np.nan,
    "monto_mediano": base_trabajo_multianual["monto_referencial_num"].median() if "monto_referencial_num" in base_trabajo_multianual.columns else np.nan,
    "fecha_min": base_trabajo_multianual["fecha_convocatoria_dt"].min() if "fecha_convocatoria_dt" in base_trabajo_multianual.columns else pd.NaT,
    "fecha_max": base_trabajo_multianual["fecha_convocatoria_dt"].max() if "fecha_convocatoria_dt" in base_trabajo_multianual.columns else pd.NaT,
}

tabla_resumen_general_multianual = pd.DataFrame([resumen_general_multianual])
guardar_csv(tabla_resumen_general_multianual, RUTA_RESULTADOS_RESUMENES / "tf_p3_resumen_general_base_principal_multianual.csv")
display(tabla_resumen_general_multianual)

# ============================================================
# COBERTURA DE VARIABLES CLAVE
# ============================================================

variables_clave = [
    "llave_convocatoria", "entidad", "tipo_entidad", "descripcion_proceso",
    "tipo_compra", "objeto_contractual", "tipo_proceso", "sistema_contratacion",
    "monto_referencial_num", "moneda", "departamento_item", "provincia_item",
    "distrito_item", "fecha_convocatoria_dt", "descripcion_item", "anio"
]

tabla_cobertura_multianual = pd.DataFrame({
    "variable": variables_clave,
    "n_validos": [base_trabajo_multianual[v].notna().sum() if v in base_trabajo_multianual.columns else np.nan for v in variables_clave],
    "pct_validos": [base_trabajo_multianual[v].notna().mean() * 100 if v in base_trabajo_multianual.columns else np.nan for v in variables_clave]
})

guardar_csv(tabla_cobertura_multianual, RUTA_RESULTADOS_TABLAS / "tf_p3_cobertura_variables_clave_multianual.csv")
display(tabla_cobertura_multianual.round(2))

# ============================================================
# MANIFEST FINAL DE ENSAMBLAJE
# ============================================================

manifest_ensamblaje = manifest_auditoria.copy()

manifest_ensamblaje["leido"] = 0
manifest_ensamblaje["integrado_base_comparativa"] = 0
manifest_ensamblaje["integrado_base_principal"] = 0

if not df_registro_lectura.empty:
    for idx, row in manifest_ensamblaje.iterrows():
        anio = str(row["anio"])
        tipo = row["tipo_descarga"]

        match = df_registro_lectura[
            (df_registro_lectura["anio"].astype(str) == anio) &
            (df_registro_lectura["tipo_descarga"] == tipo) &
            (df_registro_lectura["estado_lectura"] == "ok")
        ]

        if not match.empty:
            manifest_ensamblaje.loc[idx, "leido"] = 1
            manifest_ensamblaje.loc[idx, "integrado_base_comparativa"] = 1

            if tipo == PAQUETE_PRINCIPAL:
                manifest_ensamblaje.loc[idx, "integrado_base_principal"] = 1

guardar_csv(manifest_ensamblaje, RUTA_ADMIN / "manifest_ensamblaje_actualizado.csv")
mostrar_resumen(manifest_ensamblaje, "manifest_ensamblaje", n=20)

# ============================================================
# COBERTURA ANUAL DE LA BASE PRINCIPAL
# ============================================================

tabla_cobertura_anual = (
    base_trabajo_multianual
    .groupby("anio", as_index=False)
    .agg(
        n_registros=("llave_convocatoria", "count"),
        n_convocatorias_unicas=("llave_convocatoria", "nunique"),
        n_entidades=("entidad", "nunique"),
        n_departamentos=("departamento_item", "nunique")
    )
    .sort_values("anio")
)

guardar_csv(tabla_cobertura_anual, RUTA_RESULTADOS_RESUMENES / "tf_p3_cobertura_anual_base_principal.csv")
display(tabla_cobertura_anual)

fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(tabla_cobertura_anual["anio"].astype(str), tabla_cobertura_anual["n_registros"], marker="o")
ax.set_title("Cobertura anual de registros en la base principal multianual")
ax.set_xlabel("Año")
ax.set_ylabel("Número de registros")
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
fig.savefig(RUTA_RESULTADOS_FIGURAS / "tf_p3_cobertura_anual_base_principal.png", dpi=300, bbox_inches="tight")
plt.show()

# ============================================================
# TRAYECTORIA MENSUAL DE LA BASE PRINCIPAL
# ============================================================

if "mes_convocatoria" in base_trabajo_multianual.columns:
    tabla_mensual = (
        base_trabajo_multianual
        .dropna(subset=["mes_convocatoria"])
        .groupby("mes_convocatoria", as_index=False)
        .agg(n_registros=("llave_convocatoria", "count"))
        .sort_values("mes_convocatoria")
    )

    guardar_csv(tabla_mensual, RUTA_RESULTADOS_TABLAS / "tf_p3_convocatorias_mensuales.csv")
    display(tabla_mensual.head(20))

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(tabla_mensual["mes_convocatoria"], tabla_mensual["n_registros"], marker="o")
    ax.set_title("Evolución mensual de registros de convocatorias")
    ax.set_xlabel("Mes")
    ax.set_ylabel("Número de registros")
    ax.grid(True, alpha=0.3)
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    fig.savefig(RUTA_RESULTADOS_FIGURAS / "tf_p3_convocatorias_mensuales.png", dpi=300, bbox_inches="tight")
    plt.show()

# ============================================================
# DISTRIBUCIÓN POR OBJETO CONTRACTUAL
# ============================================================

if "objeto_contractual" in base_trabajo_multianual.columns:
    tabla_objeto = (
        base_trabajo_multianual["objeto_contractual"]
        .fillna("sin_dato")
        .value_counts(dropna=False)
        .rename_axis("objeto_contractual")
        .reset_index(name="n")
    )
    tabla_objeto["pct"] = tabla_objeto["n"] / tabla_objeto["n"].sum() * 100

    guardar_csv(tabla_objeto, RUTA_RESULTADOS_TABLAS / "tf_p3_objeto_contractual.csv")
    display(tabla_objeto.round(2))

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(tabla_objeto["objeto_contractual"], tabla_objeto["n"])
    ax.set_title("Distribución multianual por objeto contractual")
    ax.set_xlabel("Objeto contractual")
    ax.set_ylabel("Número de registros")
    ax.grid(True, axis="y", alpha=0.3)
    plt.xticks(rotation=30, ha="right")
    plt.tight_layout()
    fig.savefig(RUTA_RESULTADOS_FIGURAS / "tf_p3_objeto_contractual.png", dpi=300, bbox_inches="tight")
    plt.show()

# ============================================================
# TOP ENTIDADES POR NÚMERO DE REGISTROS
# ============================================================

if "entidad" in base_trabajo_multianual.columns:
    tabla_entidades = (
        base_trabajo_multianual["entidad"]
        .fillna("sin_dato")
        .value_counts()
        .head(20)
        .rename_axis("entidad")
        .reset_index(name="n_registros")
    )

    guardar_csv(tabla_entidades, RUTA_RESULTADOS_TABLAS / "tf_p3_top_entidades.csv")
    display(tabla_entidades)

    fig, ax = plt.subplots(figsize=(10, 7))
    ax.barh(tabla_entidades["entidad"][::-1], tabla_entidades["n_registros"][::-1])
    ax.set_title("Top 20 entidades por número de registros (multianual)")
    ax.set_xlabel("Número de registros")
    ax.set_ylabel("Entidad")
    ax.grid(True, axis="x", alpha=0.3)
    plt.tight_layout()
    fig.savefig(RUTA_RESULTADOS_FIGURAS / "tf_p3_top_entidades.png", dpi=300, bbox_inches="tight")
    plt.show()

# ============================================================
# DISTRIBUCIÓN TERRITORIAL POR DEPARTAMENTO
# ============================================================

if "departamento_item" in base_trabajo_multianual.columns:
    tabla_departamentos = (
        base_trabajo_multianual["departamento_item"]
        .fillna("sin_dato")
        .value_counts()
        .head(25)
        .rename_axis("departamento_item")
        .reset_index(name="n_registros")
    )

    guardar_csv(tabla_departamentos, RUTA_RESULTADOS_TABLAS / "tf_p3_departamentos.csv")
    display(tabla_departamentos)

    fig, ax = plt.subplots(figsize=(10, 7))
    ax.barh(tabla_departamentos["departamento_item"][::-1], tabla_departamentos["n_registros"][::-1])
    ax.set_title("Distribución multianual de registros por departamento")
    ax.set_xlabel("Número de registros")
    ax.set_ylabel("Departamento")
    ax.grid(True, axis="x", alpha=0.3)
    plt.tight_layout()
    fig.savefig(RUTA_RESULTADOS_FIGURAS / "tf_p3_departamentos.png", dpi=300, bbox_inches="tight")
    plt.show()

# ============================================================
# RESUMEN DE MONTOS
# ============================================================

if "monto_referencial_num" in base_trabajo_multianual.columns:
    tabla_montos = pd.DataFrame([{
        "n_validos": base_trabajo_multianual["monto_referencial_num"].notna().sum(),
        "promedio": base_trabajo_multianual["monto_referencial_num"].mean(),
        "mediana": base_trabajo_multianual["monto_referencial_num"].median(),
        "p25": base_trabajo_multianual["monto_referencial_num"].quantile(0.25),
        "p75": base_trabajo_multianual["monto_referencial_num"].quantile(0.75),
        "maximo": base_trabajo_multianual["monto_referencial_num"].max()
    }])

    guardar_csv(tabla_montos, RUTA_RESULTADOS_RESUMENES / "tf_p3_resumen_montos.csv")
    display(tabla_montos.round(2))

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(base_trabajo_multianual["monto_referencial_num"].dropna(), bins=50)
    ax.set_title("Distribución del monto referencial (multianual)")
    ax.set_xlabel("Monto referencial")
    ax.set_ylabel("Frecuencia")
    ax.grid(True, axis="y", alpha=0.3)
    plt.tight_layout()
    fig.savefig(RUTA_RESULTADOS_FIGURAS / "tf_p3_hist_monto_referencial.png", dpi=300, bbox_inches="tight")
    plt.show()

# ============================================================
# COBERTURA DE SUBCONJUNTOS DENTRO DE LA BASE GENERAL
# ============================================================

if col_codigo_conv is not None:
    registros_cobertura = []

    for anio in sorted(base_principal_multianual["anio"].astype(str).unique()):
        try:
            sub_general = base_principal_multianual[base_principal_multianual["anio"].astype(str) == anio]
            sub_sie = base_subasta_multianual[base_subasta_multianual["anio"].astype(str) == anio]
            sub_cd = base_contratacion_directa_multianual[base_contratacion_directa_multianual["anio"].astype(str) == anio]

            key_general = set(sub_general[col_codigo_conv].astype(str).dropna().str.strip())

            if not sub_sie.empty:
                key_sie = sub_sie[col_codigo_conv].astype(str).dropna().str.strip()
                registros_cobertura.append({
                    "anio": anio,
                    "subconjunto": "solo_subasta_inversa_electronica",
                    "n_registros": len(key_sie),
                    "pct_codigos_presentes_en_todos": (key_sie.isin(key_general)).mean() * 100 if len(key_sie) > 0 else np.nan
                })

            if not sub_cd.empty:
                key_cd = sub_cd[col_codigo_conv].astype(str).dropna().str.strip()
                registros_cobertura.append({
                    "anio": anio,
                    "subconjunto": "solo_contratacion_directa",
                    "n_registros": len(key_cd),
                    "pct_codigos_presentes_en_todos": (key_cd.isin(key_general)).mean() * 100 if len(key_cd) > 0 else np.nan
                })

        except Exception as e:
            print(f"No se pudo calcular cobertura para el año {anio}: {e}")

    tabla_cobertura_subconjuntos = pd.DataFrame(registros_cobertura)
    guardar_csv(tabla_cobertura_subconjuntos, RUTA_RESULTADOS_RESUMENES / "tf_p3_cobertura_subconjuntos_en_general.csv")
    display(tabla_cobertura_subconjuntos.round(2))

# ============================================================
# EXPLORACIÓN TEXTUAL MÍNIMA
# ============================================================

STOPWORDS_ES = {
    "de", "la", "el", "los", "las", "y", "o", "u", "en", "del", "al", "por",
    "para", "con", "sin", "un", "una", "unos", "unas", "se", "su", "sus",
    "que", "como", "a", "ante", "bajo", "contra", "desde", "durante", "entre",
    "hacia", "hasta", "mediante", "sobre", "tras", "lo", "le", "les", "es", "son",
    "ha", "han", "fue", "ser", "sea"
}

STOPWORDS_ADMIN = {
    "contratacion", "proceso", "servicio", "servicios", "adquisicion", "obra", "obras",
    "convocatoria", "item", "entidad", "contrato", "publica", "publico", "seleccion"
}

STOPWORDS_TOTALES = STOPWORDS_ES.union(STOPWORDS_ADMIN)

if "descripcion_proceso_limpia" in base_trabajo_multianual.columns:
    contador = Counter()

    for texto in base_trabajo_multianual["descripcion_proceso_limpia"].fillna(""):
        tokens = [t for t in texto.split() if len(t) >= 4 and t not in STOPWORDS_TOTALES]
        contador.update(tokens)

    top_30_tokens = pd.DataFrame(contador.most_common(30), columns=["token", "frecuencia"])
    guardar_csv(top_30_tokens, RUTA_RESULTADOS_TABLAS / "tf_p3_top_tokens_descripcion_proceso.csv")
    display(top_30_tokens)

    fig, ax = plt.subplots(figsize=(10, 7))
    ax.barh(top_30_tokens["token"][::-1], top_30_tokens["frecuencia"][::-1])
    ax.set_title("Top 30 tokens en descripción del proceso (multianual)")
    ax.set_xlabel("Frecuencia")
    ax.set_ylabel("Token")
    ax.grid(True, axis="x", alpha=0.3)
    plt.tight_layout()
    fig.savefig(RUTA_RESULTADOS_FIGURAS / "tf_p3_top_tokens_descripcion_proceso.png", dpi=300, bbox_inches="tight")
    plt.show()

# ============================================================
# TABLA MAESTRA DE OUTPUTS
# ============================================================

tabla_outputs_p3 = pd.DataFrame([
    {"output": "Base comparativa multianual", "tipo": "tabla", "carpeta": "04_datos_procesados/tablas_unificadas"},
    {"output": "Base principal multianual", "tipo": "tabla", "carpeta": "04_datos_procesados/tablas_unificadas"},
    {"output": "Base limpia de trabajo", "tipo": "tabla", "carpeta": "04_datos_procesados/tablas_limpias"},
    {"output": "Cobertura anual", "tipo": "tabla+figura", "carpeta": "07_resultados/resumenes y figuras"},
    {"output": "Trayectoria mensual", "tipo": "tabla+figura", "carpeta": "07_resultados/tablas y figuras"},
    {"output": "Distribución por objeto contractual", "tipo": "tabla+figura", "carpeta": "07_resultados/tablas y figuras"},
    {"output": "Top entidades", "tipo": "tabla+figura", "carpeta": "07_resultados/tablas y figuras"},
    {"output": "Distribución territorial", "tipo": "tabla+figura", "carpeta": "07_resultados/tablas y figuras"},
    {"output": "Resumen de montos", "tipo": "tabla+figura", "carpeta": "07_resultados/resumenes y figuras"},
    {"output": "Cobertura de subconjuntos", "tipo": "tabla", "carpeta": "07_resultados/resumenes"},
    {"output": "Exploración textual mínima", "tipo": "tabla+figura", "carpeta": "07_resultados/tablas y figuras"},
    {"output": "Manifest final de ensamblaje", "tipo": "tabla", "carpeta": "00_admin"}
])

guardar_csv(tabla_outputs_p3, RUTA_ADMIN / "tf_p3_tabla_outputs_workflow.csv")
display(tabla_outputs_p3)

# ============================================================
# BITÁCORA METODOLÓGICA DE LA PARTE 3/3
# ============================================================

bitacora_p3 = pd.DataFrame([
    {
        "paso": 1,
        "descripcion": "Carga de artefactos auditados y lectura multianual de archivos Excel",
        "salida_principal": "Base comparativa multianual"
    },
    {
        "paso": 2,
        "descripcion": "Definición de base principal y subconjuntos comparativos",
        "salida_principal": "Base principal multianual"
    },
    {
        "paso": 3,
        "descripcion": "Identificación semiautomática de variables clave",
        "salida_principal": "Tabla de variables detectadas"
    },
    {
        "paso": 4,
        "descripcion": "Construcción de la tabla limpia de trabajo",
        "salida_principal": "Base_trabajo_multianual"
    },
    {
        "paso": 5,
        "descripcion": "Producción de tablas generales de cobertura y estructura",
        "salida_principal": "Tablas resumen multianuales"
    },
    {
        "paso": 6,
        "descripcion": "Producción de visualizaciones básicas y exportaciones",
        "salida_principal": "Figuras y tablas exportadas"
    },
    {
        "paso": 7,
        "descripcion": "Actualización del manifest final de ensamblaje y cierre del workflow",
        "salida_principal": "Manifest ensamblado"
    }
])

guardar_csv(bitacora_p3, RUTA_RESULTADOS_RESUMENES / "tf_p3_bitacora_metodologica.csv")
display(bitacora_p3)

print("Parte 3/3 completada correctamente.")

print("\nArchivos clave generados:")
print("-", RUTA_TABLAS_UNIFICADAS / "tf_p3_base_paquetes_multianual_raw.csv")
print("-", RUTA_TABLAS_UNIFICADAS / "tf_p3_base_principal_multianual_raw.csv")
print("-", RUTA_TABLAS_LIMPIAS / "tf_p3_base_trabajo_multianual.csv")
print("-", RUTA_RESULTADOS_RESUMENES / "tf_p3_resumen_general_base_principal_multianual.csv")
print("-", RUTA_RESULTADOS_RESUMENES / "tf_p3_cobertura_anual_base_principal.csv")
print("-", RUTA_RESULTADOS_TABLAS / "tf_p3_objeto_contractual.csv")
print("-", RUTA_RESULTADOS_TABLAS / "tf_p3_top_entidades.csv")
print("-", RUTA_RESULTADOS_TABLAS / "tf_p3_departamentos.csv")
print("-", RUTA_RESULTADOS_RESUMENES / "tf_p3_resumen_montos.csv")
print("-", RUTA_RESULTADOS_TABLAS / "tf_p3_top_tokens_descripcion_proceso.csv")
print("-", RUTA_ADMIN / "manifest_ensamblaje_actualizado.csv")

